build: using bunup feat: dynamic python.defaultInterpreterPath docs: tweak

diff --git a/bin/link-configs b/bin/link-configs
--- a/bin/link-configs
+++ b/bin/link-configs
@@ -12,22 +12,27 @@ if [ -z "$_dir" ]; then
   exit 1
 fi
 
+if ! command -v yq > /dev/null; then
+  echo "yq not found"
+  exit 1
+fi
+
 if [ -d "$_dir/frontend" ]; then
   _frontend=frontend/
 fi
 
-if [ ! -L "$_dir/.vscode" ]; then
-  ln -sf "$_dir/${_frontend}node_modules/@postfmly/config/.vscode" "$_dir/.vscode"
+if [ -L "$_dir/.vscode" ]; then
+  unlink "$_dir/.vscode"
 fi
+ln -sf "$_dir/${_frontend}node_modules/@postfmly/config/.vscode" "$_dir/.vscode"
 
 if [ -n "$_frontend" ]; then
-  if ! command -v yq > /dev/null; then
-    echo "yq not found"
-    exit 1
-  fi
-
-  if [[ ! $(yq '."biome.configurationPath"' "$_dir/.vscode/settings.json") =~ "frontend" ]]; then
-    yq -i '."biome.configurationPath" = "./frontend/biome.json"' "$_dir/.vscode/settings.json"
-    yq -i '."biome.lsp.bin" = "./frontend/node_modules/@biomejs/biome/bin/biome"' "$_dir/.vscode/settings.json"
-  fi
+  yq -i '."biome.configurationPath" = "./frontend/biome.json"' "$_dir/.vscode/settings.json"
+  yq -i '."biome.lsp.bin" = "./frontend/node_modules/@biomejs/biome/bin/biome"' "$_dir/.vscode/settings.json"
 fi
+
+if [ -d "$_dir/backend" ]; then
+  # shellcheck disable=SC2016
+  yq -i '."python.defaultInterpreterPath" = "${workspaceFolder}/backend/.venv/bin/python"' "$_dir/.vscode/settings.json"
+fi
+
